### ISSUE TITLE
Max speed

### ISSUE THREAD

**Issue by yo90bosses** [madhephaestus/ESP32Encoder#10]
I'm working on a self balancing robot and it will have encoders on motors (two of them) and my choice is between a 13 and 500 cpr encoder and the motors will spin at a max of 20000rpm.
So I'm expecting up to 250000 pulses per motor to the ESP32. Can the library handle the 500cpr encoder or is that too fast?

**Comment by madhephaestus** [comment]
Runt pulses will be filtered out that last less than 250 ticks of APB_CLK cycles. APB_CLK usually runs at 80mhz a 4x divisor off the system frequency. you need to do some math on your end based on your configuration, but the library's critical value is 250 ticks of the  APB_CLK is the minimum pulse time, and assume at least double that speed to be stable. So the minimum pulse is calculates (250*2)/APB_CLK = minimumUs per pulse
