### ISSUE TITLE
Encoder Push Button Implementation

### ISSUE THREAD

**Issue by pvlvsk** [madhephaestus/ESP32Encoder#11]
Hello,

do you have an example how to implement the push button functionality on encoders like KY-040?

Thank you,

Andrej

**Comment by madhephaestus** [comment]
per http://henrysbench.capnfatz.com/henrys-bench/arduino-sensors-and-input/keyes-ky-040-arduino-rotary-encoder-user-manual/

C to GND
A weak pull high (done in the library anyway)
B weak pull high (done in the library anyway)
