### ISSUE TITLE
encoder using ADS1115

### ISSUE THREAD

**Issue by fotosettore** [madhephaestus/ESP32Encoder#15]
Hi !
First thanks for your work !
I'd like to use your library interfacing it with analog/digital inputs of ADS1115, due to I have not more pins available on ESP32
Is it possibile in any way ?
many thanks
peppe

**Comment by madhephaestus** [comment]
that is an I2c chip that provides a 16 bit adc, so no, that will not work. It's a chip that reads voltages, not encoder pulses. 

This library is for reading quadrature signals. https://www.dynapar.com/technology/encoder_basics/quadrature_encoder/

If you just have a voltage, look at using analogRead() on one of the pins that supports analog.
