### ISSUE TITLE
quadrature vs half quadrature

### ISSUE THREAD

**Issue by targetarchitecture** [madhephaestus/ESP32Encoder#21]
Hi,
  I'm trying to understand what type of rotary encoder I have and what the differance is between the attach methods. I'm using [https://wiki.keyestudio.com/Ks0013_keyestudio_Rotary_Encoder_Module](https://wiki.keyestudio.com/Ks0013_keyestudio_Rotary_Encoder_Module) and it works with your library , but is best method attachFullQuad or attachHalfQuad?

Thanks

John

**Comment by madhephaestus** [comment]
Either is fine, just make sure you set the pull resistors to UP.

**Comment by Rhvarrier** [comment]
What is the difference between two modes. In Readme, it is mentioned that the library can control upto 10 simultaneous encoders. In which mode does this apply ?
