### ISSUE TITLE
Reading from multiple encoders simultaneously

### ISSUE THREAD

**Issue by Rhvarrier** [madhephaestus/ESP32Encoder#23]
In the Readme, it is specified that the library supports upto 10 encoders simultaneously. But in the example sketch the encoder2 is paused before encoder1 is being read. Is this necessary?

**Comment by madhephaestus** [comment]
Each encoder object is totally independent, and you can have up to 10 objects.

**Comment by Rhvarrier** [comment]
Thank you for the clarification. So I don't need to pause one encoder while the other is being read. Both can be read simultaneously?

**Comment by madhephaestus** [comment]
correct
