### ISSUE TITLE
Double count in example

### ISSUE THREAD

**Issue by Squidyman** [madhephaestus/ESP32Encoder#28]
When running the example the encoder counts twice for every rotation of the encoder.
Using encoder: https://www.sparkfun.com/products/15141
With attachHalfQuad
ex"
Encoder count = 8
Encoder count = 8
Encoder count = 8
Encoder count = 8
Encoder count = 8
Encoder count = 10
Encoder count = 10
Encoder count = 11 ->when spinning slowly I can see the half turn signal move before skipping to 12
Encoder count = 12
Encoder count = 12
Encoder count = 13
Encoder count = 14
Encoder count = 14
Encoder count = 15
Encoder count = 16
Encoder count = 16
Encoder count = 18
Encoder count = 18
Encoder count = 18
Encoder count = 18
Encoder count = 18
Encoder count = 18
Encoder count = 20
"

**Comment by madhephaestus** [comment]
the encoder you linked uses [Grey Code](https://en.wikipedia.org/wiki/Gray_code), not quadrature. This library is for quadrature encoders only. I would not expect grey code to work.
