### ISSUE TITLE
Encoder Direction Change 

### ISSUE THREAD

**Issue by dalise** [madhephaestus/ESP32Encoder#33]
Is it possible using the current 0.3.6 library to switch the count direction without having to reverse the pin numbers using the attach function?
The scenario here is where an encoder is mounted 'reversed' depending on the application. 
I currently have a flag that is set if the encoder is "inverted" and therefore I could address this on startup with the attach function but would prefer the ability to change it on the fly.

**Comment by madhephaestus** [comment]
no, and thats a normal way to deal with encoder count direction. Reversing the A and B pins would so the same, either in code or physically.
