### ISSUE TITLE
Debounce

### ISSUE THREAD

**Issue by paulh002** [madhephaestus/ESP32Encoder#41]
Hi, I use this library a lot and works quite well, only with mechanical encoders I still have issues with debouncing the inputs. I made a small change to the attach function to add a debounce value which is now fixed in the library.  Maybe a valuable change. 
	
// In the include file have debounce assigned default value to keep library compatibility
        void attachHalfQuad(int aPintNumber, int bPinNumber, int debounce = 250);
	void attachFullQuad(int aPintNumber, int bPinNumber, int debounce = 250);
	void attachSingleEdge(int aPintNumber, int bPinNumber, int debounce = 250);

void ESP32Encoder::attach(int a, int b, enum encType et, int debounce) 
in the attach function
	// Filter out bounces and noise
	pcnt_set_filter_value(unit, debounce);  // Filter Runt Pulses pcnt_set_filter_value(unit, 250); 

void ESP32Encoder::attachHalfQuad(int aPintNumber, int bPinNumber, int debounce) {
	attach(aPintNumber, bPinNumber, half, debounce);

}
void ESP32Encoder::attachSingleEdge(int aPintNumber, int bPinNumber, int debounce) {
	attach(aPintNumber, bPinNumber, single, debounce);
}
void ESP32Encoder::attachFullQuad(int aPintNumber, int bPinNumber, int debounce) {
	attach(aPintNumber, bPinNumber, full, debounce);
}

**Comment by madhephaestus** [comment]
This is addressed in the API, and documented here: https://github.com/madhephaestus/ESP32Encoder#a-note-on-ky-040-and-similar
