### ISSUE TITLE
PlatformIO: Make compile for Arduino 2.0.1-RC1

### ISSUE THREAD

**Issue by tueddy** [madhephaestus/ESP32Encoder#48]
Hi,

thank's for your library! Works fine with PlatformIO Arduino 1.0.6!

Switching to 2.0.1-RC1 i get a compiler error, PNCT undefined.

Fix:
Insert this line to ESP32Encoder.cpp:
`#include <soc/pcnt_struct.h>`

Now i can compile both 1.0.6 and 2.0.1-RC

Best 
Dirk

**Comment by madhephaestus** [comment]
Released this change as of 0.6.0

**Comment by whogarden** [comment]
Version V0.6.0 compile and is working fine with Arduino core for the ESP32 release v2.0.1
Thank you.
