### ISSUE TITLE
acceleration support

### ISSUE THREAD

**Issue by TehseenHasan** [madhephaestus/ESP32Encoder#53]
please add rotary encoder acceleration (fast count) support when rotating the encoder fastly.

**Comment by madhephaestus** [comment]
Im afraid this is out of scope for this module. It is a position only module and you only get data when you look at it. It is not calculating rates of change anywhere as there is not fixed time base check. To do a feature like this you would need to make a thread to wrap your encoder with polled reads and calculate the velocity and acceleration that way.
