### ISSUE TITLE
Question about the if statement in the attach method of ESP32Encoder class

### ISSUE THREAD

**Issue by armuren** [madhephaestus/ESP32Encoder#54]
Many thanks for this excellent library! The examples worked immediately with no effort, the code is clear and well documented and I learned quite a bit reading it.

My only question is regarding the [if statement](https://github.com/madhephaestus/ESP32Encoder/blob/master/src/ESP32Encoder.cpp#L128) in the attach method.  That check seems to be undoing everything that was done from lines 110 to just before the if statement.  There's also an `else` which similarly undoes everything before it.  

What's even stranger is that there's  a [ternary operator](https://github.com/madhephaestus/ESP32Encoder/blob/master/src/ESP32Encoder.cpp#L117) a few lines above that accomplishes the same thing as the `if/else`.

I am not an embedded engineer but I have been writing software for a number of years.  I am missing something?

**Comment by madhephaestus** [comment]
yeah, there is some nasty code duplication there, should b e cleaned up at some point...
