### ISSUE TITLE
Would be great to have...

### ISSUE THREAD

**Issue by nodoubtman** [madhephaestus/ESP32Encoder#63]
Hello.

It would be great to have a min and a max function.

thank you.
Marc.

**Comment by madhephaestus** [comment]
I dont understand what this is suggesting...

**Comment by nodoubtman** [comment]
I mean set a min and a max value.

**Comment by madhephaestus** [comment]
It is an encoder reader, so there is no such thing as a min nor max value. If you want values capped, that should be done in user code.

**Comment by nodoubtman** [comment]
SetFilter set the max value, right ?
Thanks.

**Comment by madhephaestus** [comment]
Did you read the documentation? https://madhephaestus.github.io/ESP32Encoder/classESP32Encoder.html let me know what didn't make sense in the documentation.
