### ISSUE TITLE
[Question] What do Full , Half, and Single mean?

### ISSUE THREAD

**Issue by human890209** [madhephaestus/ESP32Encoder#76]
Hi, I'm confused by the mode names. I can't found any doc or wiki about them.

**Comment by madhephaestus** [comment]
full and half quadrature, and single edge count mode. https://en.wikipedia.org/wiki/Rotary_encoder#/media/File:Incremental_directional_encoder.gif

Full performs a count increment on all 4 edges, half on the rising and falling of a single channel, and single counts just the rising edge of the A channel.

**Comment by madhephaestus** [comment]
I added an explanation and link to the wikipedia page on incremental encoders.

**Comment by human890209** [comment]
Thanks!
