### ISSUE TITLE
erroneous count-up on sup period rotation using SingelEdge

### ISSUE THREAD

**Issue by 404-baitnotfound** [madhephaestus/ESP32Encoder#8]
when using attachSingelEdge() I get erroneous count-up by wiggling the encoder shaft.
Using attachHalfQuad I get correct half step counts.

This is most likely due to the incorrect edge triggering of the ESP32.  (but don't quote me on that)

To ignore singel count changes I wrote following code in my loop:

```
int32_t encoder_position = 0;

void loop() {
  
  uint16_t enc_delta = abs(encoder.getCountRaw() - (encoder_position*2)) / 2;
  if(encoder.getCountRaw() > (encoder_position*2)){
    encoder_position += enc_delta;
  }
  else{
    encoder_position -= enc_delta;
  }
}
```

**Comment by madhephaestus** [comment]
no, thats expected behavior in single edge mode. Single edge mode is for counting button presses NOT quadrature style encoders.

**Comment by 404-baitnotfound** [comment]
ok how is single edge mode intended to be used with buttons?  It still requires two pins?

**Comment by madhephaestus** [comment]
give the same pin value for both, or connect the pins together
